/**
 * src/application/exporters/walkthroughExporter.ts
 *
 * Exporters for automated walkthrough guides generated by the route solver.
 * Generates formatted Markdown, Steam Community Guide BBCode, and plain text.
 */

import { downloadBlob } from "../downloadHelper.ts";
import type { SolvedWalkthrough } from "../../domain/index.ts";

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function formatMarkdownCodeSpan(value: string): string {
  const clean = value.replace(/[\r\n]+/g, " ");
  if (!clean.includes("`")) {
    return `\`${clean}\``;
  }
  const match = clean.match(/`+/g);
  const maxBackticks = match ? Math.max(...match.map((m) => m.length)) : 1;
  const delimiter = "`".repeat(maxBackticks + 1);
  return `${delimiter} ${clean} ${delimiter}`;
}

function sanitizeHeading(value: string): string {
  return value.replace(/[\r\n]+/g, " ").replace(/^#+\s*/, "").replace(
    /`/g,
    "\\`",
  ).trim();
}

export function exportWalkthroughToMarkdown(
  walkthrough: SolvedWalkthrough,
): string {
  const lines: string[] = [];

  lines.push(
    `# Walkthrough Guide: ${sanitizeHeading(walkthrough.targetLabel)}\n`,
  );

  // Summary Metadata
  lines.push("## Summary\n");
  lines.push(
    `- **Target Ending / Label**: ${
      formatMarkdownCodeSpan(walkthrough.targetLabel)
    }`,
  );
  if (walkthrough.endingType) {
    lines.push(`- **Ending Classification**: \`${walkthrough.endingType}\``);
  }
  lines.push(`- **Total Steps**: ${walkthrough.totalSteps}`);
  lines.push(`- **Key Decisions Required**: ${walkthrough.totalChoices}`);
  lines.push(
    `- **Estimated Playthrough Time**: ${walkthrough.formattedReadingTime}`,
  );
  lines.push(
    `- **Total Dialogue Volume**: ~${walkthrough.totalWordCount.toLocaleString()} words (${walkthrough.totalDialogueCount} dialogue lines)`,
  );
  if (walkthrough.chaptersTraversed.length > 0) {
    lines.push(
      `- **Chapters Visited**: ${walkthrough.chaptersTraversed.join(", ")}`,
    );
  }
  lines.push("");

  // Condition Flags
  const flagKeys = Object.keys(walkthrough.flagsNeeded);
  if (flagKeys.length > 0) {
    lines.push("## Required Condition Flags & Variables\n");
    lines.push(
      "To successfully reach this outcome, the following game state conditions must be met:\n",
    );
    lines.push("| Flag / Variable | Required Condition / Value |");
    lines.push("| :--- | :--- |");
    for (const key of flagKeys) {
      const val = walkthrough.flagsNeeded[key];
      const safeKey = escapeMarkdownTableCell(key);
      const safeVal = escapeMarkdownTableCell(String(val));
      lines.push(`| \`${safeKey}\` | \`${safeVal}\` |`);
    }
    lines.push("");
  }

  // Step-by-step instructions
  lines.push("## Step-by-Step Decision Checklist\n");
  lines.push(
    "Follow these choices sequentially from the start of the story:\n",
  );

  let stepNumber = 1;
  for (const step of walkthrough.steps) {
    if (step.type === "start") {
      lines.push(
        `- [ ] **Step ${stepNumber}**: Begin new game at \`${step.nodeLabel}\`${
          step.chapter ? ` *(${step.chapter})*` : ""
        }`,
      );
      stepNumber++;
    } else if (step.type === "choice") {
      lines.push(
        `- [ ] **Step ${stepNumber}**: At menu **${
          step.menuLabel ?? "Choice"
        }**, choose: **"${
          step.choiceText ?? "Select option"
        }"** → proceeds to \`${step.nodeLabel}\``,
      );
      stepNumber++;
    } else if (step.type === "decision_branch") {
      if (step.conditionExpression) {
        lines.push(
          `- [ ] **Step ${stepNumber}**: At branch point \`${step.nodeLabel}\`, ensure condition is satisfied: \`${step.conditionExpression}\``,
        );
        stepNumber++;
      }
    } else if (
      step.type === "ending" || step.nodeId === walkthrough.targetNodeId
    ) {
      lines.push(
        `- [x] **Goal**: Reach **\`${step.nodeLabel}\`** *(Ending unlocked!)* 🎉`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

export function exportWalkthroughToSteamGuide(
  walkthrough: SolvedWalkthrough,
): string {
  const lines: string[] = [];

  lines.push(`[h1]Walkthrough: ${walkthrough.targetLabel}[/h1]\n`);

  lines.push("[b]Summary[/b]");
  lines.push(`• Target Outcome: [b]${walkthrough.targetLabel}[/b]`);
  if (walkthrough.endingType) {
    lines.push(`• Classification: ${walkthrough.endingType}`);
  }
  lines.push(`• Estimated Time: ${walkthrough.formattedReadingTime}`);
  lines.push(`• Key Choices: ${walkthrough.totalChoices}`);
  lines.push(
    `• Words: ~${walkthrough.totalWordCount.toLocaleString()} words\n`,
  );

  const flagKeys = Object.keys(walkthrough.flagsNeeded);
  if (flagKeys.length > 0) {
    lines.push("[b]Required Variables / Flags[/b]");
    lines.push("[spoiler]");
    for (const key of flagKeys) {
      lines.push(`• ${key}: ${String(walkthrough.flagsNeeded[key])}`);
    }
    lines.push("[/spoiler]\n");
  }

  lines.push("[h2]Step-by-Step Choices[/h2]");
  let stepNumber = 1;
  for (const step of walkthrough.steps) {
    if (step.type === "start") {
      lines.push(
        `[b]${stepNumber}.[/b] Start story at [code]${step.nodeLabel}[/code]`,
      );
      stepNumber++;
    } else if (step.type === "choice") {
      lines.push(
        `[b]${stepNumber}.[/b] Menu [b]${
          step.menuLabel ?? "Choice"
        }[/b]: Select [spoiler]"${step.choiceText ?? "Option"}"[/spoiler]`,
      );
      stepNumber++;
    } else if (step.type === "decision_branch" && step.conditionExpression) {
      lines.push(
        `[b]${stepNumber}.[/b] Condition check: [code]${step.conditionExpression}[/code]`,
      );
      stepNumber++;
    } else if (
      step.type === "ending" || step.nodeId === walkthrough.targetNodeId
    ) {
      lines.push(
        `[b]Result:[/b] Reach ending [b]${step.nodeLabel}[/b]!`,
      );
    }
  }

  return lines.join("\n");
}

export function exportWalkthroughToText(
  walkthrough: SolvedWalkthrough,
): string {
  const lines: string[] = [];

  lines.push(`=======================================================`);
  lines.push(` WALKTHROUGH GUIDE: ${walkthrough.targetLabel.toUpperCase()}`);
  lines.push(`=======================================================\n`);

  lines.push(`Target: ${walkthrough.targetLabel}`);
  if (walkthrough.endingType) {
    lines.push(`Classification: ${walkthrough.endingType}`);
  }
  lines.push(`Estimated Time: ${walkthrough.formattedReadingTime}`);
  lines.push(`Choices Required: ${walkthrough.totalChoices}`);
  lines.push(
    `Word Count: ~${walkthrough.totalWordCount.toLocaleString()} words`,
  );
  lines.push(
    `Chapters: ${walkthrough.chaptersTraversed.join(", ") || "Main"}\n`,
  );

  const flagKeys = Object.keys(walkthrough.flagsNeeded);
  if (flagKeys.length > 0) {
    lines.push(`REQUIRED FLAGS:`);
    for (const key of flagKeys) {
      lines.push(`  - ${key}: ${String(walkthrough.flagsNeeded[key])}`);
    }
    lines.push("");
  }

  lines.push(`CHOICE STEPS:`);
  let stepNumber = 1;
  for (const step of walkthrough.steps) {
    if (step.type === "start") {
      lines.push(`  [${stepNumber}] Start at: ${step.nodeLabel}`);
      stepNumber++;
    } else if (step.type === "choice") {
      lines.push(
        `  [${stepNumber}] At "${step.menuLabel ?? "Menu"}" -> CHOOSE: "${
          step.choiceText ?? "Option"
        }"`,
      );
      stepNumber++;
    } else if (step.type === "decision_branch" && step.conditionExpression) {
      lines.push(
        `  [${stepNumber}] Condition needed: ${step.conditionExpression}`,
      );
      stepNumber++;
    } else if (
      step.type === "ending" || step.nodeId === walkthrough.targetNodeId
    ) {
      lines.push(`  >>> UNLOCKED ENDING: ${step.nodeLabel} <<<`);
    }
  }

  lines.push(`\n=======================================================`);
  return lines.join("\n");
}

export function downloadWalkthrough(
  walkthrough: SolvedWalkthrough,
  format: "markdown" | "steam" | "text" = "markdown",
): void {
  const safeFilename = (walkthrough.targetLabel || "walkthrough")
    .replace(/[^a-zA-Z0-9_-]/g, "_")
    .toLowerCase();

  let content: string;
  let filename: string;
  let mime: string;

  if (format === "steam") {
    content = exportWalkthroughToSteamGuide(walkthrough);
    filename = `${safeFilename}_steam_guide.txt`;
    mime = "text/plain;charset=utf-8";
  } else if (format === "text") {
    content = exportWalkthroughToText(walkthrough);
    filename = `${safeFilename}_walkthrough.txt`;
    mime = "text/plain;charset=utf-8";
  } else {
    content = exportWalkthroughToMarkdown(walkthrough);
    filename = `${safeFilename}_walkthrough.md`;
    mime = "text/markdown;charset=utf-8";
  }

  const blob = new Blob([content], { type: mime });
  void downloadBlob(blob, filename);
}
